import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
          My Posts
        </h1>

        <ul className={styles.ul}>
          <li>
            <p className={styles.postContent}>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quaerat corrupti, eum rerum amet perferendis ipsum voluptate qui vel voluptas maiores.</p>
            <p className={styles.postDate}>9/28/2021</p>
          </li>
          <li>
            <p className={styles.postContent}>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quaerat corrupti, eum rerum amet perferendis ipsum voluptate qui vel voluptas maiores.</p>
            <p className={styles.postDate}>9/28/2021</p>
          </li>
          <li>
            <p className={styles.postContent}>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quaerat corrupti, eum rerum amet perferendis ipsum voluptate qui vel voluptas maiores.</p>
            <p className={styles.postDate}>9/28/2021</p>
          </li>
        </ul>

        <form>
          <textarea className={styles.formInput}></textarea>
          <button className={styles.formButton}>Add New Post</button>
        </form>

      </main>
    </div>
  )
}
